BEGIN TRANSACTION;
INSERT INTO "supermanzer_projectsection" ("id","class_string","is_markdown","text","project_id","heading") VALUES (1,'problem-statement',true,'I started programming because I thoguht it was fun to start telling the machines what to do, rather than the other way around.  After working through many coding tutorials in Python, JavaScript, and HTML I had picked up the practice of creating TODO comments to highlight where I had left the state of my code and my intent for what should come next.  This has proved rather helpful in keeping track of what I thought was needed and whwere my code was going.  However, as my projects grew more modular and spread across more files, tracking down these comments was not always easy.',1,''),
 (2,'solution',true,'After using the `os` module in Python and particularly the `os.walk()` method to traverse all files and subdirectories in a directory, it occurred to me that one could very easily write a program to scan all files in a directory for TODO comments, so that is what I did.  As with many projects, what started out laughably simple quickly got more complex as I realized what little tweaks would make it more functional.  However, I am pleased to have created something that does the job in just over 100 lines of code (including length doc strings and comments).',1,''),
 (3,'goal',true,'While many current IDEs have features to collect and catalog these comments, my goal with this project was to produce something that would be part of a public (or private) repository and work to improve collaboration.  I envisioned this being used by teams to communicate where one coder had to call it quits and where the next one to pick up the project could get started.  Also it would be useful if a solo developer had to walk away from a project for a while and wanted to pick it up again later, from a hosted repository.',1,''),
 (4,'motivation',true,'This project was initially writtin in `MATLAB`.

Once I started getting into the coding and research work for my M.Sc. thesis, I had to do a lot of work with NDBC buoy data.  For those of you who don''t know, the federal government maintains a large number of buoy stations around the world oceans monitoring oceanographic conditions.  This data is freely available (cool, right?) but the format can sometimes be a pain to deal with (plain `.txt` files or weird archive files).  

After doing an initial gathering of data by hand (downloading text files and manually entering the commands to load & stitch them together), I realized how even a need to simply change the months/years I was examining would take a lot more work.  I also realized _it shouldn''t_!',2,'Motivation'),
 (5,'solution',true,'With this in mind, and realizing that the webmaster(s) at NOAA kept their URL conventions reliably static for a reason, I defined a class (first in `MATLAB`, now in `Python`) that would allow the user to simply specify the range of years and/or months for which data is needed.  With this info my class would perform a series of http requests, parse the data from the text files returned, and return the data as a property of the object instantiated.

Most of the features I''ve built into this were based on the struggles I had when beginning my research. Here are a few examples:
  * `get_station_metadata()`:  This crawls the specific data station''s website for a table of parameters and saves the useful metadata like lat, lon, sensor types and positions, etc., to the DataBuoy instance.

  * `station_search()`:  When your advisor says "this is great but how does it correspond with measurements from nearby buoys?", this is the function you want to use.  I have provided two methods (box and radial) but for my money, the radial search is the really cool one.  This is because, if you''ve already used the function above, you can just specify a distance (in km) and it will perform a radial search for all the data stations with the radius you provided.  Then you''ve got a list of IDs to get you started.',2,'Solution'),
 (6,'',true,'I think, before too many people start actually using this thing, I want to clean up the API.  While I appreciate verbosity and clarity, some names are just too long and provide too much opportunity for typos.

I would also like to not rely on dictionaries too much for data containers and figure out how best to use objects so I can provide clean dot notation access to all data properties.

Greater metadata would likely also be useful to ensure that, when a researcher is ready to write up their work, they have all the information they need without having to go hunting for it.',2,'Next Steps');
INSERT INTO "supermanzer_project" ("id","date_created","date_modified","title","github_url","image_url","summary") VALUES (1,'2020-09-04','2020-09-05','TODO Catalog - CLA','https://github.com/supermanzer/todo-cla','/images/code-typing.jpeg','A command line application that scans a code base and generates a TODO.md that logs all TOOO comments in project directory, written in Python'),
 (2,'2020-09-04','2020-09-04','NDBC Data Buoy Reader','https://github.com/GenSci/NDBC','/images/buoy.jpg','A Python package designed to automate the fetching and organizing of National Data Buoy Center (NDBC) standard meteorological data.  Additionally it provides station metadata and station search functionality.');
INSERT INTO "django_session" ("session_key","session_data","expire_date") VALUES ('1sfrfbcvc6h9x9nqiyziujta37z4qhbi','.eJxVjDsOwjAQBe_iGllx_F1Kes5g7a4NDiBbipMKcXcSKQW0b-bNW0RclxLXnuc4JXEWSpx-N0J-5rqD9MB6b5JbXeaJ5K7Ig3Z5bSm_Lof7FyjYy_bG7G5p0AkCau1Gle2o0Qcmx2Qge0JnDBoawBkYgleBQW15skxAVovPF-l7OAE:1kEIgU:scV0c8i3G1xRxaEuXQ5qviqNcGOTMOiWVVTBmeAVqrI','2020-09-18 20:51:46.792485');
INSERT INTO "auth_user" ("id","password","last_login","is_superuser","username","last_name","email","is_staff","is_active","date_joined","first_name") VALUES (1,'pbkdf2_sha256$216000$USKVX8XNpq7g$7h/bF5bLmS/S9D30f0UnsJHp3eOkj+1HytCdekS78eo=','2020-09-04 20:51:46.787051',true,'ryan','','',true,true,'2020-09-04 20:25:56.621972','');

COMMIT;
