version: "3"

services:
  api:
    restart: "always"
    build:
      context: .
      dockerfile: api_Dockerfile
    volumes:
      - .:/src/app
    ports:
      - "8000:8000"
    command: ./start_server.sh
    env_file:
      - .env
    depends_on:
      - db

  db:
    restart: always
    image: $PG_IMAGE
    expose:
      - "5432"
    env_file:
      - .env
    ports:
      - "5433:5432"

volumes:
  pg-data: {}
