version: "3"

services:
  api:
    restart: "always"
    build:
      context: .
      dockerfile: api_Dockerfile
    volumes:
      - .:/src/app
    command: ./start_server.sh
    env_file:
      - .env
    depends_on:
      - db

  db:
    restart: always
    image: $PG_IMAGE
    expose:
      - "5432"
    env_file:
      - .env
    ports:
      - "5433:5432"

  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    ports:
      - "8123:80"

volumes:
  pg-data: {}
